# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Sphinx build
        run: |
          sudo chown -R runner:runner /usr/local/bin
          wget -P /usr/local/bin https://github.com/jgm/pandoc/releases/download/3.1/pandoc-3.1-linux-amd64.tar.gz
          tar -xf /usr/local/bin/pandoc-3.1-linux-amd64.tar.gz --directory /usr/local/bin/
          cp /usr/local/bin/pandoc-3.1/bin/pandoc /usr/local/bin/pandoc
          echo | ls /usr/local/bin
          pandoc --help
          sphinx-build docs/sphinx docs/sphinx/_build
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/_build/
          force_orphan: true
