# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Sphinx build
        run: |
          wget -P $GITHUB_WORKSPACE/pandoc https://github.com/jgm/pandoc/releases/download/3.1/pandoc-3.1-linux-amd64.tar.gz
          tar -xf $GITHUB_WORKSPACE/pandoc/pandoc-3.1-linux-amd64.tar.gz --directory $GITHUB_WORKSPACE/pandoc
          echo "$GITHUB_WORKSPACE/pandoc/pandoc-3.1/bin" >> $GITHUB_PATH
          echo "First"
          echo ls $GITHUB_PATH
          echo "Second"
          echo ls $GITHUB_WORKSPACE/pandoc/pandoc-3.1/bin
          pandoc --help
          sphinx-build docs/sphinx docs/sphinx/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/sphinx/_build/
          force_orphan: true
